### PR TITLE
Block package search calls if matching block_tags

### PR DESCRIPTION
**Pull request by kentsanggds**
## What

Block calls to package search if they match all block tags and log a warning when it does this.

### CODE REVIEW

**Comment by risicle** [comment]
Mind is a little blown that either CKAN or solr doesn't handle this for us.

**Review by risicle — APPROVED** [review]
Definitely looks like it does what it says it does. Whether that is the right thing to do here, I don't know.

**Comment by risicle** [comment]
Ah my reviews don't mean anything anymore.

**Comment by kentsanggds** [comment]
Solr upgrade does handle this so this is extra insurance.

**Review by thomasleese — APPROVED** [review]

**Pull request merged**
